### ISSUE TITLE
spotify-status-to-instagram-notes 

### ISSUE THREAD

**Issue by PaZIVAL0001** [ghrlt/spotify-status-to-instagram-notes#1]
 python3.10 app.py
Traceback (most recent call last):
  File "/home/runner/spotify-status-to-instagram-notes/app.py", line 71, in <module>
    App().start()
  File "/home/runner/spotify-status-to-instagram-notes/app.py", line 11, in __init__
    self.spotify = spotify.Client()
  File "/home/runner/spotify-status-to-instagram-notes/spotify.py", line 23, in __init__
    self.refreshSession()
  File "/home/runner/spotify-status-to-instagram-notes/spotify.py", line 98, in refreshSession
    with open(self.session_file_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/spotify-status-to-instagram-notes/spotify.session'
exit status 1


**Comment by ghrlt** [comment]
Fixed in commit c9229a0ae748d04fc8458a39f5a5e9f5198b0bef

Have fun with this project!
